[project]
name = "workspace-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agentic-sandbox",
    "cloud-sql-python-connector[asyncpg]>=1.20.0",
    "fastapi[standard]>=0.128.0",
    "kubernetes>=35.0.0",
]

[tool.uv.sources]
agentic-sandbox = { git = "https://github.com/kubernetes-sigs/agent-sandbox.git", subdirectory = "clients/python/agentic-sandbox-client", rev = "main" }
