[project]
name = "workspace-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agentic-sandbox",
    "fastapi[standard]>=0.128.0",
    "google-auth>=2.48.0",
    "google-cloud-container>=2.62.0",
]

[tool.uv.sources]
agentic-sandbox = { git = "https://github.com/kubernetes-sigs/agent-sandbox.git", subdirectory = "clients/python/agentic-sandbox-client", rev = "main" }
