apiVersion: v1
kind: Service
metadata:
  name: workspace-api
  namespace: default
spec:
  # Change this to ClusterIP to use with GKE Gateway
  type: ClusterIP 
  selector:
    app: workspace-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080